version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env  # Load environment variables from .env

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env  # Load environment variables for the database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
